USE PROJECT4;

SELECT*FROM country;
SELECT*FROM state;
SELECT*FROM city;

INSERT INTO country VALUES
('INDIA'),
('USA'),
('CHINA'),
('NEPAL')
;

INSERT INTO state VALUES
('BIHAR',1),
('PUNJAB',1),
('UP',1),
('ALASKA',2),
('CALIFORNIA',2),
('FLORIDA',2),
('BEIJING',3),
('SHANGHAI',3),
('TIANJIN',3),
('BAGMATI',4),
('GANDAKI',4),
('LUMBINI',4)
;

INSERT INTO city VALUES
('PATNA',1),
('GAYA',1),
('AMRTISAR',2),
('LUDHIANA',2),
('AGRA',3),
('GHAZIABAD',3),
('ANCHORAGE',4),
('HOMER',4),
('LOS ANGELES',5),
('SAN FRANCISCO',5),
('MIAMI',6),
('ORLANDO',6),
('DONGCHENG DISTRICT',7),
('CHAOYANG DISTRICT',7),
('HUANGPU DISTRICT',8),
('PUTUO DISTRICT',8),
('HEDONG DISTRICT',9),
('DONGLI DISTRICT',9),
('KATHMANDU',10),
('GODAWARI',10),
('POKHARA',11),
('GORKHA',11),
('BUTWAL',12),
('BHAIRAHAWA',12)
;