/* CREATE DATABASE JobPortalDb; */

USE JobPortalDb;
GO

CREATE TABLE USER_MASTER(
Id INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(100),
LastName VARCHAR(100),
Password VARCHAR(500),
Email VARCHAR(100),
Mobile VARCHAR(15),
Gender VARCHAR(15),
IsLogin TINYINT,
IsLocked TINYINT,
Locked_DateTime DATETIME,
UnLocked_DateTime DATETIME,
RetryCount TINYINT,
CreatedOn DATETIME,
UpdatedOn DATETIME,
Status TINYINT
);
GO

CREATE TABLE EMPLOYER_DETAILS(
Id INT PRIMARY KEY IDENTITY,
UserMasterId INT,
UserId INT,
CompanyName VARCHAR(100),
Location VARCHAR(100),
GST_Number VARCHAR(100),
CompanyType VARCHAR(100),
CompanyLogo VARCHAR(100),
CreatedOn DATETIME,
UpdatedOn DATETIME,
Status TINYINT
);
GO

CREATE TABLE EMPLOYEE_DETAILS(
Id INT PRIMARY KEY IDENTITY,
UserMasterId INT,
UserId INT,
ProfileImage VARCHAR(500),
LatestCV VARCHAR(500),
Status TINYINT
);
GO

CREATE TABLE ADDRESS(
Id INT PRIMARY KEY IDENTITY,
UserMasterId INT,
Address1 VARCHAR(200),
Address2 VARCHAR(200),
Country INT,
State INT,
City INT,
Pincode INT,
LandMark VARCHAR(100),
AddressType VARCHAR(100),
CreatedOn DATETIME,
UpdatedOn DATETIME,
Status TINYINT
);
GO

CREATE TABLE EMPLOYEE_EXPERIENCE(
Id INT PRIMARY KEY IDENTITY,
UserMasterId INT,
FromYearMonth DATETIME,
ToYearMonth DATETIME,
CompanyName VARCHAR(100),
Designation VARCHAR(100),
CTC DECIMAL,
ExpectedCTC DECIMAL,
NoticePeriods DATETIME,
IsCurrentCompany VARCHAR(100),
JobDescription VARCHAR(500),
Status TINYINT
);
GO

CREATE TABLE EDUCATIONAL_DETAILS(
Id INT PRIMARY KEY IDENTITY,
UserMasterId INT,
University VARCHAR(100),
CollegeName VARCHAR(100),
CourseType VARCHAR(100), /* LIKE REGULAR OR PRIVATE */
EducationType VARCHAR(100), /* LIKE 10TH, 12TH, GRADUATION, DIPLOMA OR MASTER */
CourseName VARCHAR(100),
PassingYearMonth DATETIME,
Percentage DECIMAL,
CreatedOn DATETIME,
UpdatedOn DATETIME,
Status TINYINT
);
GO

CREATE TABLE VERIFY_ACCOUNT(
Id INT PRIMARY KEY IDENTITY,
UserId INT,
OTP INT,
SendDateTime DATETIME
);
GO

CREATE TABLE JOB_POSTING(
Id INT PRIMARY KEY IDENTITY,
CompenyId INT, 
JobTitle VARCHAR(100),
JobDescription VARCHAR(200),
TotalPosition INT,
AnnualCTC DECIMAL,
Location VARCHAR(100),
Experience VARCHAR(200),
WorkMode VARCHAR(100),
CreatedOn DATETIME,
UpdatedOn DATETIME,
Status TINYINT
);
GO

CREATE TABLE JOB_SKILLS(
Id INT PRIMARY KEY IDENTITY,
JobId INT,
Skills VARCHAR(100)
);
GO

CREATE TABLE JOB_APPLIED(
Id INT PRIMARY KEY IDENTITY,
JobId INT,
UserId INT,
AppliedDateTime DATETIME,
Status TINYINT
);